apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ .Values.component }}
spec:
  # modify replicas according to your case
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      initContainers:
        - name: parameters-pull
          image: docker.io/krn010/parameter-store-init-container-image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: "dev.roboshop.cart.REDIS_HOST,REDIS_HOST dev.roboshop.cart.CATALOGUE_HOST,CATALOGUE_HOST dev.roboshop.cart.CATALOGUE_PORT,CATALOGUE_PORT"

      containers:
        - name: {{ .Values.component }}
          image: docker.io/krn010/{{ .Values.component }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters

      volumes:
        - name: parameters
          emptyDir: {}
